name = "DiscriminantVariety"
uuid = "2f58a086-0456-416b-a47b-60f2de8c8644"
authors = ["Alexander Demin", "Christina Katsamaki", "Fabrice Rouillier"]
version = "0.0.3"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AbstractAlgebra = "0.44, 0.45, 0.46, 0.47"
Groebner = "0.10"
Nemo = "0.48, 0.49, 0.50, 0.51, 0.52, 0.53"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
